version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19 
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Running terraform fmt"
      - terraform fmt -check
      - echo "Running terraform plan"
      - terraform plan -out=tfplan

artifacts:
  files:
    - tfplan # Store the Terraform plan file as an artifact if needed