version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Running terraform fmt"
      - terraform fmt   # Automatically formats the files
      - echo "Running terraform plan"
      - terraform plan -out=tfplan  # Generate the tfplan output file
      - echo "Applying terraform configuration"
      - terraform apply --auto-approve tfplan  # Apply the changes defined in the plan

  post_build:
    commands:
      - echo "Deploying file to S3..."
      - aws s3 cp amzn_batch_id_reset/s3/static_files/ s3://amzn-batch-id-012025/ --recursive

artifacts:
  files:
    - tfplan  # Make sure terraform plan generates tfplan file and upload it as an artifact.
